# Jekyll config for good.but.cheap
# using the Agency theme

url: "https://good.but.cheap"

title: Good But Cheap
email: contact@good.but.cheap
description: Reviews, with a focus on adequacy!
author: The Good But Cheap Team

collections:
  reviews:
    output: true
    permalink: /review/:title

defaults:
  - scope:
      path: ""
      type: "reviews"
    values:
      layout: "review"

plugins:
  - jekyll-remote-theme

remote_theme: raviriley/agency-jekyll-theme